// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("server.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "IELTS",
                            Name = "IELTS"
                        },
                        new
                        {
                            Id = 2,
                            Code = "JLPT",
                            Name = "JLPT"
                        });
                });

            modelBuilder.Entity("server.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseType")
                        .HasColumnType("text");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("server.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EN",
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "JP",
                            Name = "Japanese"
                        });
                });

            modelBuilder.Entity("server.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LessonType")
                        .HasColumnType("text");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("server.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("ExamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "5.5",
                            Description = "Band 5.5",
                            ExamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "6.0",
                            Description = "Band 6.0",
                            ExamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "6.5",
                            Description = "Band 6.5",
                            ExamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "7.0",
                            Description = "Band 7.0",
                            ExamId = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "N5",
                            Description = "N5",
                            ExamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "N4",
                            Description = "N4",
                            ExamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = "N3",
                            Description = "N3",
                            ExamId = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "N2",
                            Description = "N2",
                            ExamId = 2
                        },
                        new
                        {
                            Id = 9,
                            Code = "N1",
                            Description = "N1",
                            ExamId = 2
                        });
                });

            modelBuilder.Entity("server.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("server.Models.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionImage")
                        .HasColumnType("text");

                    b.Property<string>("OptionText")
                        .HasColumnType("text");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("server.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("ExamId")
                        .HasColumnType("integer");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("LevelId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("server.Models.TestQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<string>("Skill")
                        .HasColumnType("text");

                    b.Property<int?>("TestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("TestQuestions");
                });

            modelBuilder.Entity("server.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LevelId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TargetLanguageId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetLevelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TargetLanguageId");

                    b.HasIndex("TargetLevelId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("server.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("server.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("server.Models.UserSpeaking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AiScore")
                        .HasColumnType("real");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSpeakings");
                });

            modelBuilder.Entity("server.Models.UserTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BandEstimate")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<int?>("TestId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTestResults");
                });

            modelBuilder.Entity("server.Models.UserWriting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AiScore")
                        .HasColumnType("real");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserWritings");
                });

            modelBuilder.Entity("server.Models.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Meaning")
                        .HasColumnType("text");

                    b.Property<string>("Pronunciation")
                        .HasColumnType("text");

                    b.Property<string>("Word")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LevelId");

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("server.Models.VocabularyAudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<int?>("VocabularyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.ToTable("VocabularyAudios");
                });

            modelBuilder.Entity("server.Models.VocabularyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VocabularyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.ToTable("VocabularyImages");
                });

            modelBuilder.Entity("server.Models.Exercise", b =>
                {
                    b.HasOne("server.Models.Lesson", "Lesson")
                        .WithMany("Exercises")
                        .HasForeignKey("LessonId");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("server.Models.Lesson", b =>
                {
                    b.HasOne("server.Models.Topic", "Topic")
                        .WithMany("Lessons")
                        .HasForeignKey("TopicId");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("server.Models.Level", b =>
                {
                    b.HasOne("server.Models.Exam", "Exam")
                        .WithMany("Levels")
                        .HasForeignKey("ExamId");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("server.Models.Question", b =>
                {
                    b.HasOne("server.Models.Exercise", "Exercise")
                        .WithMany("Questions")
                        .HasForeignKey("ExerciseId");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("server.Models.QuestionOption", b =>
                {
                    b.HasOne("server.Models.Question", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("server.Models.Test", b =>
                {
                    b.HasOne("server.Models.Exam", "Exam")
                        .WithMany("Tests")
                        .HasForeignKey("ExamId");

                    b.HasOne("server.Models.Level", "Level")
                        .WithMany("Tests")
                        .HasForeignKey("LevelId");

                    b.Navigation("Exam");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("server.Models.TestQuestion", b =>
                {
                    b.HasOne("server.Models.Test", "Test")
                        .WithMany("TestQuestions")
                        .HasForeignKey("TestId");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("server.Models.Topic", b =>
                {
                    b.HasOne("server.Models.Language", "Language")
                        .WithMany("Topics")
                        .HasForeignKey("LanguageId");

                    b.HasOne("server.Models.Level", "Level")
                        .WithMany("Topics")
                        .HasForeignKey("LevelId");

                    b.Navigation("Language");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.HasOne("server.Models.Language", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("TargetLanguageId");

                    b.HasOne("server.Models.Level", "TargetLevel")
                        .WithMany()
                        .HasForeignKey("TargetLevelId");

                    b.Navigation("TargetLanguage");

                    b.Navigation("TargetLevel");
                });

            modelBuilder.Entity("server.Models.UserAchievement", b =>
                {
                    b.HasOne("server.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.UserProgress", b =>
                {
                    b.HasOne("server.Models.Lesson", "Lesson")
                        .WithMany("UserProgresses")
                        .HasForeignKey("LessonId");

                    b.HasOne("server.Models.User", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.UserSpeaking", b =>
                {
                    b.HasOne("server.Models.TestQuestion", "Question")
                        .WithMany("UserSpeakings")
                        .HasForeignKey("QuestionId");

                    b.HasOne("server.Models.User", "User")
                        .WithMany("UserSpeakings")
                        .HasForeignKey("UserId");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.UserTestResult", b =>
                {
                    b.HasOne("server.Models.Test", "Test")
                        .WithMany("UserTestResults")
                        .HasForeignKey("TestId");

                    b.HasOne("server.Models.User", "User")
                        .WithMany("UserTestResults")
                        .HasForeignKey("UserId");

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.UserWriting", b =>
                {
                    b.HasOne("server.Models.TestQuestion", "Question")
                        .WithMany("UserWritings")
                        .HasForeignKey("QuestionId");

                    b.HasOne("server.Models.User", "User")
                        .WithMany("UserWritings")
                        .HasForeignKey("UserId");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.Vocabulary", b =>
                {
                    b.HasOne("server.Models.Language", "Language")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LanguageId");

                    b.HasOne("server.Models.Level", "Level")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LevelId");

                    b.Navigation("Language");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("server.Models.VocabularyAudio", b =>
                {
                    b.HasOne("server.Models.Vocabulary", "Vocabulary")
                        .WithMany("VocabularyAudios")
                        .HasForeignKey("VocabularyId");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("server.Models.VocabularyImage", b =>
                {
                    b.HasOne("server.Models.Vocabulary", "Vocabulary")
                        .WithMany("VocabularyImages")
                        .HasForeignKey("VocabularyId");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("server.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("server.Models.Exam", b =>
                {
                    b.Navigation("Levels");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("server.Models.Exercise", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("server.Models.Language", b =>
                {
                    b.Navigation("Topics");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("server.Models.Lesson", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("server.Models.Level", b =>
                {
                    b.Navigation("Tests");

                    b.Navigation("Topics");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("server.Models.Question", b =>
                {
                    b.Navigation("QuestionOptions");
                });

            modelBuilder.Entity("server.Models.Test", b =>
                {
                    b.Navigation("TestQuestions");

                    b.Navigation("UserTestResults");
                });

            modelBuilder.Entity("server.Models.TestQuestion", b =>
                {
                    b.Navigation("UserSpeakings");

                    b.Navigation("UserWritings");
                });

            modelBuilder.Entity("server.Models.Topic", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Navigation("UserAchievements");

                    b.Navigation("UserProgresses");

                    b.Navigation("UserSpeakings");

                    b.Navigation("UserTestResults");

                    b.Navigation("UserWritings");
                });

            modelBuilder.Entity("server.Models.Vocabulary", b =>
                {
                    b.Navigation("VocabularyAudios");

                    b.Navigation("VocabularyImages");
                });
#pragma warning restore 612, 618
        }
    }
}
